spring.application.name=tavarsystem

# =============================================================================
#                              JWT CONFIG
# =============================================================================
jwt.secret=your-256-bit-secret-key-here-make-it-at-least-32-bytes-long


# =============================================================================
#                              H2 DATABASE
# =============================================================================
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect